[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION                     = "20"
  NEXT_PUBLIC_GOOGLE_CLIENT_ID     = "631574178472-imq0mlh3hopqmpnac68f3i8hhiqjb9jc.apps.googleusercontent.com"

[[redirects]]
  from   = "/.netlify/functions/check-premium"
  to     = "/api/check-premium"
  status = 200
  force  = true

[[redirects]]
  from   = "/.netlify/functions/stripe-webhook"
  to     = "/api/stripe-webhook"
  status = 200
  force  = true
