[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP         = "true"
  NODE_VERSION                     = "20"
  NEXT_PUBLIC_GOOGLE_CLIENT_ID     = "631574178472-imq0mlh3hopqmpnac68f3i8hhiqjb9jc.apps.googleusercontent.com"
